### PR TITLE
Profile picture Component 

### PR DESCRIPTION
**Pull request by kevinbece5**
profile picture component for comments done

### CODE REVIEW

**Review by Cowie22 — APPROVED** [review]

**Review by pon-y — CHANGES_REQUESTED** [review]
Please conform to AirBnB style guide.

**Comment by kevinbece5** [comment]
hey @pon-y  fixed those issues you wanted

**Review by sharmoo — COMMENTED** [review]
profilePic module => spelling error on line 6

**Comment by pon-y** [comment]
Looks good! Thank you.

**Review by pon-y — APPROVED** [review]

**Pull request merged**
